#!/bin/bash

echo 'Add docker repo'
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
echo 'Add kuber repo'
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" >> /etc/apt/sources.list
echo "deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-xenial main" >> /etc/apt/sources.list
echo 'Install packages'
apt-get update
apt-get -y --allow-unauthenticated install docker-ce=5:18.09.9~3-0~ubuntu-bionic docker-ce-cli=5:18.09.9~3-0~ubuntu-bionic kubeadm=1.16.2-00 kubelet=1.16.2-00 kubernetes-cni=0.7.5-00 bridge-utils

rm -f /home/vagrant/.kube/config

iptables -t nat -F
iptables -F 
iptables -X

echo 'Delete docker0 bridge'
ip link set docker0 down
ip link delete docker0

echo 'nameserver 8.8.8.8' > /etc/resolv_up.conf
echo '172.16.1.100   master' >> /etc/hosts
echo '172.16.1.101   worker01' >> /etc/hosts
echo '172.16.1.102   worker02' >> /etc/hosts

echo 'Update kubelet config and restart kubelet'
cat <<EOF > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_EXTRA_ARGS=--node-ip=172.16.1.101"
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
# the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet \$KUBELET_KUBECONFIG_ARGS \$KUBELET_CONFIG_ARGS \$KUBELET_KUBEADM_ARGS \$KUBELET_EXTRA_ARGS
EOF

systemctl daemon-reload
systemctl restart kubelet.service

echo 'Join the master'
kubeadm join --token anilre.soopersecrethere 172.16.1.100:6443 --discovery-token-unsafe-skip-ca-verification
